# Generated by Django 2.1.7 on 2019-04-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
