# Generated by Django 2.1.7 on 2019-04-25 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_favourites'),
        ('articles', '0004_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesDislikesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=False, null=True)),
                ('event_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='likesdislikesmodel',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='likesdislikesmodel',
            name='user_liking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_liking', to='profiles.Profile'),
        ),
    ]
